### ISSUE TITLE
Episode not found error message on /episodes page

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#1]
Sometimes I get the green `Sorry, that episode is unavailable at the moment. Please check back soon.` on the /episodes page

**Comment by vallieres** [comment]
Screenshot of the issue:

![Image](https://d17oy1vhnax1f7.cloudfront.net/items/0o3q213h1j2B1O3G2T2F/Image%202016-10-04%20at%2011.18.50%20AM.png?v=9e5dde8d)

**Comment by dan** [comment]
@chadbailey59 I've seen this also, not sure how to reproduce consistently. I don't think it's a caching thing.

**Comment by dan** [comment]
Fixed.
