### ISSUE TITLE
[Bug] Sponsorship "Share" is only viewable by admins

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside#100]
Maybe I don't understand the feature, but my assumption is this is a link we can share with our sponsors so they can listen and view stats for the episode they sponsored. When I open the share link in incognito it just redirects to my home page.

**Comment by dan** [comment]
Please provide the share link so we can take a look.

**Comment by jamesmontemagno** [comment]
Hmmm they all now say "we're sorry, but something went wrong". Maybe something else was changed. I'll file a ticket for it.

**Comment by jamesmontemagno** [comment]
Works now!
