### ISSUE TITLE
Unable to use /40 for new episode

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#102]
It says it's already been used. However, we are at 39 at the moment (and have a 0 trailer episode).

![Error](https://d3uepj124s5rcx.cloudfront.net/items/2a0r422s1Z23111l3O2q/Image%202017-03-03%20at%203.45.48%20PM.png?v=d4bd561a)

Here's the episode list:

![Episode List](https://d3uepj124s5rcx.cloudfront.net/items/1T0D1r2P1a2E1f2h3Q3r/Image%202017-03-03%20at%203.47.10%20PM.png?v=67c96a6e)

I also checked if we had any redirects using this url and we did not.

I tried to save the episode without an MP3, like a private draft. Maybe that's the issue?

**Comment by vallieres** [comment]
Tried with an .mp3 file and I still get the error. had to save it with 41. help!

**Comment by vallieres** [comment]
https://rgba.fireside.fm/admin/episodes/6a87495c-05fa-4567-98f4-c561ca4c9eb3/edit

**Comment by vallieres** [comment]
Doh! Used 40 for an older @vallieres title... Move along.. nothing to see!

**Comment by dan** [comment]
Please file a support ticket for support issues. Github is used for sharing ideas/suggestions/feature reqs.

Thanks!
