### ISSUE TITLE
[Feature Request] Second Tier & sorting for hosts

### ISSUE THREAD

**Issue by timmitra** [firesidelabs/fireside#104]
We recently had a host resign. We had four regular hosts, so we are now down to three. Also since the hosts are listed alphabetically, the resigner would come up first. Would it be possible to sort hosts and maybe "bench" hosts who aren't active? I know that we can select the hosts per episode, but sorting would be helpful.

**Comment by dan** [comment]
Sorting is a good idea, I like it. As far as benching, just change their status to "Private" and they won't appear anymore.

**Comment by timmitra** [comment]
Dan, I know this is closed... but I don't want to mark the host as private, since he did participate in past episodes. So he's entitled to having credit for being on the show and sharing his thoughts. If I mark him as private, he disappears from the publicly facing episode info.
