### ISSUE TITLE
[Feature Request] Improve Embedded Audio Player

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside#107]
I think a few tweaks here could make HUGE improvements.

* The title of the show doesn't show up anywhere or gets cut off
* The speed up control gets cut off
* The length of the episode doesn't show up, not sure if that is possible to fix at all

![image](https://cloud.githubusercontent.com/assets/1676321/25018922/a2d3990e-203d-11e7-81a3-e34245eb09cb.png)

**Comment by jamesmontemagno** [comment]
One additional thing would be if we can add additional speed modifications...

1.5x for me is wayyy too fast. On PocketCast I uses 1.1 or 1.2 based on the podcast.

**Comment by dan** [comment]
Are you still seeing these errors?

**Comment by jamesmontemagno** [comment]
I am @dan 
https://blog.xamarin.com/podcast-app-monetization-net-standard-azure-cosmos-db/
or http://motzcod.es/post/162402194007/plugins-for-xamarin-go-dotnet-standard
