### ISSUE TITLE
Feed Content-Type

### ISSUE THREAD

**Issue by Cj-Malone** [firesidelabs/fireside#109]
Currently the RSS feeds are returned with the ```Content-Type: text/xml; charset=utf-8```, it would be better for it to be ```Content-Type: application/rss+xml; charset=utf-8```. That way browsers on Android devices will automatically hand the feed off to a podcast client instead of trying to display the feed in the browser.

See ```curl -I http://the.worknotwork.show/rss | grep "Content-Type:"``` or ```curl -I http://linuxactionnews.com/rss | grep "Content-Type:"```

**Comment by Cj-Malone** [comment]
I've also just noticed this [feed](http://linuxactionnews.com/rss) contains `<duration>1821</duration>`. This isn't a native RSS tag, I assume you meant to use the iTunes `duration` tag. However that needs to be formatted like `<itunes:duration>30:21</itunes:duration>` or `<duration xmlns="http://www.itunes.com/dtds/podcast-1.0.dtd">30:21</duration>`

**Comment by dan** [comment]
This was fixed.

**Comment by Cj-Malone** [comment]
@dan The content type is still set as `text/xml` not `application/rss+xml`.
