### ISSUE TITLE
Link Bookmarklet doesn't sort by episode number

### ISSUE THREAD

**Issue by ddysart** [firesidelabs/fireside#11]
https://files.slack.com/files-tmb/T0GVBJUAZ-F2K8PD1HB-0467c29a8e/screen_shot_2016-10-04_at_11.31.44_am_720.png

Not sure what it's sorting by

**Comment by dan** [comment]
Fixed. Sorting was by episode number, which ya'll recently downvoted and wanted switched to slug. So now we sort by `publish_at`.
