### ISSUE TITLE
Embedded player in sponsorship Share page doesn't play

### ISSUE THREAD

**Issue by jaxzin** [firesidelabs/fireside#110]
When attempting to test the Share page for a Sponsorship I created, the embedded player does not play the track. It appears to queue up the show, places the playhead in the right spot but if I hit play it just stutters and doesn't play the sound of the ad.

Tested on Google Chrome 58.0.3029.110 on Windows 10.

**Comment by dan** [comment]
Is this still not working correctly for you? If not, could you please file a support ticket?

Thanks!
