### ISSUE TITLE
Controllable Focal Point for Images

### ISSUE THREAD

**Issue by tcgannon** [firesidelabs/fireside#111]
A while back [Medium](http://medium.com) introduced a feature that enables the user to control the focal point of the image during the automated cropping process.  It's pretty well executed...you simply ctrl-click on the spot that you want centred when the image is cropped.  For instance, I usually want to keep the eyes of a person's face in the centre of the image (or at least visible) when it's cropped.  Medium's approach would be great, but an interim implementation could be to simply specify X and Y values.  I would be willing to do that to get the feature more quickly.

**Comment by dan** [comment]
Interesting. I'll investigate.
