### ISSUE TITLE
User given unclear error during signup if user name includes a capital letter

### ISSUE THREAD

**Issue by CameronBanga** [firesidelabs/fireside#15]
#### *Quick Description*
When signing up for an account on Fireside, the user is asked to enter a designer user name / user handle. If the user enters a username that includes a capital letter (ex, ButterfieldDietPodcast), an unclear error message is presented to the user explaining "Slug can't contain capitals"

#### *Reproducibility*

1. Attempt to create a new account using a valid request code.
2. When prompted for an account user name / handle, enter in a name with a capital letter, such as "MrSparkle".

#### *Expected Results*
User can proceed, and either capital letters are allowed, or Fireside automatically converts case to lowercase .

#### *Actual Results*
User is presented with an error explaining "Slugs can't contain capitals"

#### *Configuration and Scope*

* macOS Sierra 10.12.0
* Safari 10.0

#### *Other Notes*

Also experienced by Slack user Kerstin when setting up her account.

**Comment by dan** [comment]
Fixed with better descriptions, and now we allow capital letters too.

**Comment by dan** [comment]
(Will be in next deploy)
