### ISSUE TITLE
No line breaks with links in description

### ISSUE THREAD

**Issue by joshuacole** [firesidelabs/fireside#16]
When you have multiple links, there's no line breaks in the description separating them so they all run together.

![img_0841](https://cloud.githubusercontent.com/assets/1606203/19126683/bd48ff64-8af0-11e6-9c38-3976de3cf7ef.PNG)

**Comment by dan** [comment]
Fixed - now set as bulleted items (`<li>`) within a list (`<ul>`) just like on the web page.
