### ISSUE TITLE
MP3's not updating after adding cover art.

### ISSUE THREAD

**Issue by joshuacole** [firesidelabs/fireside#17]
I uploaded a new MP3 first (with no embedded cover art) then added the art using the Cover Art field in Fireside and the MP3 didn't update. 

The cover art shows itself in the episode field, but when I download the MP3, the cover art is the default cover art for the show, not the custom cover art I uploaded.

**Comment by dan** [comment]
Episodes should be triggered to reprocess their MP3 files if cover art is added/changed/removed.

**Comment by dan** [comment]
Fixed this.
