### ISSUE TITLE
Allow podcast tags to have their own RSS feed

### ISSUE THREAD

**Issue by CameronBanga** [firesidelabs/fireside#18]
#### *Quick Description*
Fireside has the awesome ability to add tags to an episode of a podcast. When viewing an episode page, a listener can click on a tag and be presented with a list of all episodes that include this tag. 

It would be very neat if each tag page (http://www.watchoutforfireballs.com/tags/Mario) could have it's own RSS feed. This would make it easier for listeners to subscribe to a show but only receive episodes of a specific topic. 

It would also make it easier for hosts to easily have an "All Episodes" feed in iTunes/Overcast, etc, while also having specific niche shows or "Best Of"'s all managed under the same system. 

#### *Additional Notes and Related Systems*

Slack chat from October 6, 2016 at 3:42 PM CT in #general 

```
cameronbanga [3:20 PM]  
@dan I could move this to features, or make a ticket, but any consideration in the future to where tags for a show could have their own RSS feed? So like @koleross's link above would have a feed that gave only Mario shows?

[3:21]  
I think of shows like the Incomparable, which always has a bunch of kinda sub shows, and that always felt messy to me

[3:22]  
Though the tags would maybe be less discoverable, could be awesome for creators who want to do a "Best Of" or something

dan [3:32 PM]  
That’s absolutely in the plan (same thing for host feeds), but yes please do add a feature req for it
```

**Comment by dan** [comment]
+1

Tags and hosts should also get their own feeds.

**Comment by dan** [comment]
Done.

Find the tag-rss-feed links on each tag page, such as:

https://monsterinmypod.fireside.fm/tags/Monstrous%20Manual

Link is like:

https://monsterinmypod.fireside.fm/tags/Monstrous%20Manual/rss
