### ISSUE TITLE
Renaming podcast URL does not redirect old feed

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#19]
I just renamed our podcast from:
`https://rgbafm.fireside.fm`
to
`https://rgba.fireside.fm`

And https://rgbafm.fireside.fm/rss still loads it's own content. It's probably up to date, but shouldn't it redirect to the new URL?

**Comment by dan** [comment]
I get a 404 on that page. Perhaps something is cached in your browser/app?

**Comment by vallieres** [comment]
Yes, it was cache. Shouldn't it redirect to the new URL with a 301 instead of giving our a 404? What about people that subscribed to the old-name.fireside.fm/rss ?
