### ISSUE TITLE
About Page does not contain social sharing links

### ISSUE THREAD

**Issue by CameronBanga** [firesidelabs/fireside#2]
#### *Quick Description*
In the Fireside admin panel, (https://making-the-bands.fireside.fm/admin/settings for my show), I've set a couple social links for the show to Facebook, Twitter, etc. But I don't see them appearing on my About page, or anywhere on the podcast page. I see social sharing for hosts, but not for the podcast. 

#### *Reproducibility*

1. Add social links under the Settings page for a podcast

#### *Expected Results*
See these links appear on a podcast About page, or on the home page for a show.

#### *Actual Results*
I can't find my hot and spicy social links.

#### *Configuration and Scope*

* macOS Sierra 10.12.0
* Safari 10.0

**Comment by dan** [comment]
Fixed. Will be in next deploy.
