### ISSUE TITLE
Hosts website requires fully qualified URL 

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#23]
When entering a website in the add/edit hosts page, entering a website requires the entire fully-qualified URL.  Entering something like "whatever.com" will be rejected, you need to include the http:// as well. I think if this was missing from the submitted string you could probably make an assumption and add it - especially because most sites would redirect from http to https automatically if required.

**Comment by dan** [comment]
Across the board, Fireside-wide, we require that http:// or https:// be entered in any URL (with perhaps one specific exception). This was a conscious decision on my part, and I think it makes the most sense for now.

What was missing, though, was help text that explains that the http:// is required, as well as placeholder example text, so I'm adding that now.
