### ISSUE TITLE
Force fireside url to redirect to custom domain

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#24]
If I have a custom domain specified for my podcast, it would be nice if the standard generated *whatever*.fireside.fm URL would automatically redirect to the custom domain I've entered.

**Comment by danbetcher** [comment]
On a side note (not sure if this should be a separate issue), the link shown in the "Podcast" section of the dashboard should perhaps also reflect the custom domain I've entered, rather than the default fireside-generated one.

**Comment by dan** [comment]
I've been thinking a lot about this. I'm on the fence about forwarding for some edge-case technical reasons, but it's something I'm generally in favor of.

**Comment by danbetcher** [comment]
Yeah, edge-cases can be tricky for that sort of thing... is an optional checkbox a possibility, or would that make things needlessly too complex?

**Comment by dan** [comment]
Squarespace handles this by allowing the user to set either the custom domain or the squarespace subdomain as "default" and redirects the other non-default one to the default.

Maybe we could do something similar, allow users to set either the custom domain or the subdomain as _primary_ with a checkbox as you've suggested.

**Comment by dan** [comment]
And, done.
