### ISSUE TITLE
Admin panel left navigation is not accessible on mobile devices

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#25]
Other than the 4 main sections that can be accessed from the dashboard links, there is no way to access the other areas of the admin panel (such as metrics)  without rotating my phone to landscape mode - there is no indication or visual cues telling me that I would need to do that.

**Comment by ckhicks** [comment]
Been poking at this and I think I found a good solution. Going to compare notes with Dan and pursue that direction - thanks for the good find!

**Comment by dan** [comment]
Would love to see your notes, @ckhicks.

**Comment by ckhicks** [comment]
My approach is to make the entire left-hand menu accessible on smaller viewports, which has been working well so far and just needs a bit more testing. Almost there.

**Comment by danbetcher** [comment]
I'd be happy to help with testing if you need an extra set of eyes. I've got a pretty healthy stack of test devices too.

**Comment by ckhicks** [comment]
Just added a couple fixes for these - next deploy we should have more to test against.

**Comment by dan** [comment]
Fixed.
