### ISSUE TITLE
Hosts pages do not seem to render well on mobile 

### ISSUE THREAD

**Issue by CraftyDeano** [firesidelabs/fireside#28]
Hey team,

See screenshot and example URL below. 

You can replicate by viewing URL on a mobile device or resizing your browser so its width matches mobile devices. 

Problem: The avatar is oversized and the top is out of bounds, also the host name and the podcast title are misplaced and oversized. 

Example URL: http://codenamechicken.church/hosts/karl
![img_0357](https://cloud.githubusercontent.com/assets/2019053/19253869/21af55ee-8f46-11e6-94d3-183a498919f0.PNG)

**Comment by shoemoneypod** [comment]
I was just about to post this, but you beat me to it. 💯 
![img_0063](https://cloud.githubusercontent.com/assets/22759543/19256864/bb102280-8f38-11e6-8be8-2a51635f1941.PNG)

**Comment by CraftyDeano** [comment]
It looks like the avatar is to blame. Shrinking it fixes the alignment of everything else. 

![fullsizerender](https://cloud.githubusercontent.com/assets/2019053/19263860/4e54c9bc-8f96-11e6-90ac-3d24d7d9fc66.jpg)
![fullsizerender 2](https://cloud.githubusercontent.com/assets/2019053/19263861/4e5cbbf4-8f96-11e6-9b6c-363897fc2e5b.jpg)

**Comment by dan** [comment]
Fixed!

**Comment by shoemoneypod** [comment]
Thanks Dan, as usual!
