### ISSUE TITLE
Request: Create migration plan from Squarespace to Fireside

### ISSUE THREAD

**Issue by jen729w** [firesidelabs/fireside#29]
As per [my slack comment](https://firesideteam.slack.com/archives/general/p1476001021001054):

I’m going to migrate away from Sqsp to Fireside (yay!) but can’t figure out the redirect … let me know if I’m being daft here. 

The RSS URL is currently http://strangeattractor.fm/episode?format=rss. That’s hosted at Sqsp but obviously I’m using my own domain.

As soon as I flip that domain over to Fireside, that URL will disappear. Podcast broken, right?

I _think_, therefore, I have to do this:
1. Set up Fireside alongside Squarespace; the two run concurrently, for a while.
2. While they’re running concurrently, set up a redirect on Sqsp.
3. Give it some time (a month?).
4. Update iTunes etc. in the background.
5. Cancel Sqsp, hoping that all of my subscribed clients have hit the site, got the redirect, and are now reading from Fireside.

**Comment by jen729w** [comment]
I've decided just to give this a go - I know enough about DNS not to *totally* shaft the whole thing.

Maybe.

Anyway, I'll keep meticulous notes and send them over assuming all is well. Just FYI.

**Comment by idbjorh** [comment]
I'm in this situation as well.  It would be nice to be able to add URL redirects in Fireside for this purpose.

**Comment by dan** [comment]
Redirects were added a while back, so I'm closing this one up.
