### ISSUE TITLE
Metrics for All-Time vs Episode comparison doesn't seem to be correct

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#31]
I've got 6 episodes in fireside now, and looking at the Metrics page, there's been 204 all-time total downloads, but underneath that it shows the episode comparison, which is showing the top episode also has 204 downloads... but the graph next to it seems to spread those numbers out, so something isn't adding up correctly.

See screenshot for details
<img width="991" alt="screen shot 2016-10-11 at 9 31 12 pm" src="https://cloud.githubusercontent.com/assets/2416372/19295457/5331f1ee-8ffa-11e6-896d-f1a6b8439a4b.png">

In case it's a bit of a unique situation, All 6 of those episodes were imported from Squarespace where we used to host the podcast, so none of them have actually aired originally on fireside. Not sure if that's skewing the numbers in someway or not.

**Comment by danbetcher** [comment]
To follow up on this, it doesn't look like it's limited to imported episodes. I've also added a couple new shows directly from the fireside app now, and its still all lumped together.

**Comment by chadbailey59** [comment]
This was resolved with a bugfix a few weeks ago. Sorry for leaving the issue open!
