### ISSUE TITLE
Adding sponsorships from the sponsorships tab in an episode throws and error

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#32]
When editing an episode, if I click the "Sponsorships" tab, and then click the "+ New Sponsorship" button in the top-right corner, I get a big nasty error.

<img width="1027" alt="screen shot 2016-10-11 at 10 02 28 pm" src="https://cloud.githubusercontent.com/assets/2416372/19296098/c5dab2c2-8ffe-11e6-86f9-06e2a0584211.png">

Error message:

<img width="611" alt="screen shot 2016-10-11 at 10 02 35 pm" src="https://cloud.githubusercontent.com/assets/2416372/19296108/d1b4e400-8ffe-11e6-9eb5-a16b5d35eff5.png">

**Comment by dan** [comment]
Fixed.
