### ISSUE TITLE
404 On a BG image

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#36]
Getting this in the console. Not sure what it relates to.

`Failed to load resource: the server responded with a status of 404 (Not Found) https://rgba.fireside.fm/assets/themes/adminflare/body-bg.png`

From the https://rgba.fireside.fm/admin/metrics page

Also, this one too:

`https://rgba.fireside.fm/assets/themes/adminflare/menu-bg.png`

**Comment by dan** [comment]
@ckhicks I think `rgba` is @vallieres podcast slug, but I'm not sure why these aren't being included.

**Comment by vallieres** [comment]
Yes it is :)

**Comment by vallieres** [comment]
Initially it was rgbafm but I renamed it rgba 🙂 maybe that's a lead?

**Comment by ckhicks** [comment]
@dan Looks like this is an image path issue globally in the admin. I'll compare notes with you before pushing the fix here to make sure it works perfectly.

**Comment by ckhicks** [comment]
@vallieres We spent some solid time on this the other day - are you still seeing any missing images?

**Comment by vallieres** [comment]
I browsed around and was not able to replicate it. :lgtm:

**Comment by ckhicks** [comment]
Excellent - let us know if you spot any more flukes.
