### ISSUE TITLE
Metrics, Click on Podcast Client bars, give an error

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#37]
The graph bars seems to be clickable in the Podcast Client, but does not seem to go anywhere.

Tries to load `https://rgba.fireside.fm/admin/undefined`

Shouldn't it jump to the bottom of the page where we have the left side menu and select the appropriate one?

**Comment by dan** [comment]
Yeesh. @chadbailey59 will handle.

**Comment by chadbailey59** [comment]
Pixed in upcoming PR.
