### ISSUE TITLE
Front-end Subscribe page shows fireside URL instead of custom domain

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#38]
I've specified a custom domain in the admin panel, but when I visit the `/subscribe` page on the front-end site, it still shows the fireside URL instead of my custom URL.

Not a big deal, but if I'm promoting my custom domain, it would be good if it was consistent across the board.

**Comment by dan** [comment]
Fixed. You may need to do a quick podcast settings update to see it (just click Update, you don't need to change anything).
