### ISSUE TITLE
Episode list looks off if an episode does not have a header image.

### ISSUE THREAD

**Issue by CameronBanga** [firesidelabs/fireside#39]
#### _Quick Description_

NOTE, this only occurs if the podcast has added any header image for a previous show. So for example, if a show has 3 episodes (like mine in this example), and 2 episodes have header images, and 1 episode does not.

I started adding header image to my podcast, but forgot to add one for my last episode. After going to my page today to share the show with a friend, I noticed that the episode list looked a bit off, as one episode did not have an image, but the previous two did. So I went ahead and added one for my latest episode. 

From a technical perspective, I get why this is the case, and it seems to be working as intended. My only thought/issue is that, as we start adding a couple dozen shows, it seems likely that some episodes will not have a reasonable header image that makes sense. But it will forever look weird to have empty header images when compared to the other episodes in the list. So now, I am forced to have a header image for every episode.
#### _Reproducibility_
1. Go to show's main landing page, (https://making-the-bands.fireside.fm for my show)
2. Scroll down to the episode list
#### _Expected Results_

If an episode does not have an episode specific header image, I would suggest one of the following situations to occur:
1. Use the podcast's primary and default header image as a background.
2. Create an assortment (a dozen or so?) of different generic patterns that could be loaded in by default, if an episode does not have a header image. This would provide the same sort of effect that occurs when there is an episode image (background image provides an easy to recognize bounding box for the table cell), and would look snazzy.
#### _Actual Results_

Here's an example of how this currently works/looks: 

![napkin 10-14-16 10 23 19 am](https://cloud.githubusercontent.com/assets/611354/19392883/3b0a7ad2-91f8-11e6-89e0-ae6256ccc63a.png)
#### _Configuration and Scope_
- Safari 10.0
- Sierra 10.12.0

Don't think this matters, but ¯_(ツ)_/¯
#### _Additional Notes and Related Systems_

I really like Fireside so far.

**Comment by dan** [comment]
We use alternating gray colors for the backgrounds. See here:

https://roadwork.fireside.fm

If you put header images, they replace the grey color, but the alternating colors continue.

**Comment by bynines** [comment]
It is quite jarring. There are a few approaches we could take in "fixing" this, so I'll go over those with you a.s.a.p, @dan. Thank you very much for this feedback, @CameronBanga!

**Comment by dan** [comment]
The quickest fix would be to just not show artwork there. Thoughts?

**Comment by bynines** [comment]
@dan, is this resolved with the addition of the default header image?
