### ISSUE TITLE
Social Networks Defined are Not Displayed on Site (hidden in code)

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#4]
We set the twitter, facebook youtube, etc, but they are nowhere to be found.

I noticed they are commented out in the code related to the nav menu. If uncommented, the CSS does not handle them properly.

![Source Code with Hidden Social Networks](https://d17oy1vhnax1f7.cloudfront.net/items/3i3J2d0O3a0D3K1q0t39/Image%202016-10-04%20at%2011.39.34%20AM.png?v=907a2144)

**Comment by dan** [comment]
They are displayed (now) on the About page. We will work on some ideas for displaying them on the main page at some point, also.

**Comment by dan** [comment]
@bynines Any thoughts on this?

**Comment by bynines** [comment]
I've made some adjustments, however we need to test internally. If these are approved, then we can deploy as soon as they are 👍

**Comment by dan** [comment]
They are on the about page now, and will soon be on the main page.
