### ISSUE TITLE
Episode posting time is incorrect (possibly DST issue?)

### ISSUE THREAD

**Issue by mamstergrub** [firesidelabs/fireside#40]
I posted this episode at 5pm PDT, but it shows the posting time as 4:00pm. I wonder if Fireside is ignoring DST in my time zone?

![screenshot_135](https://cloud.githubusercontent.com/assets/22843038/19396832/cf8d3162-91f9-11e6-9171-fdb80b6c29e5.png)

**Comment by dan** [comment]
That's possible, I'll investigate.

**Comment by chadbailey59** [comment]
Sorry for the delay here... what's the name of your podcast, and is that episode still in place?
