### ISSUE TITLE
Can't preview an episode page when podcast is set private

### ISSUE THREAD

**Issue by mamstergrub** [firesidelabs/fireside#41]
I'm testing out Fireside and have my podcast set to Private in the Settings tab. I want to preview an episode page, but it doesn't work. If I set the episode to Public, Fireside takes me to a private page at my Fireside subdomain, and the server won't serve it. If I set the episode to Private, I get this:
![screenshot_134](https://cloud.githubusercontent.com/assets/22843038/19396909/35c58542-91fa-11e6-8233-0f0c5f21af7f.png)
The URL generated is: https://mamster.fireside.fm/preview/MWcql59I

**Comment by dan** [comment]
Do you have an mp3 uploaded? Do you have a date in the past? That will help me test.

**Comment by mamstergrub** [comment]
Yes, if you go into my Fireside, you should be able to see it there. The MP3 isn't a podcast, just a random sound file, but it shouldn't matter, right? And the date is yesterday, I think. Let me know if I need to give you permissions or anything.

**Comment by dan** [comment]
No matter what I do, I can't seem to reproduce this.

- If I set the date to a date in the past or future, it works.
- If I set the visibility to private, unlisted, or public, it works.

Not sure what I'm missing.

Could you please explain the exact steps you take when creating an episode that fails this way so I can see it exactly?

**Comment by mamstergrub** [comment]
I ended up deleting my beta account because I wasn't hosting any live content and wasn't ready to start paying. Could you please send me a new invitation? I'm happy to give it another try.

**Comment by dan** [comment]
@mamstergrub Sure, let me know when you're ready to try really hosting a show -- I want to save beta slots for people who are interested in hosting their podcasts with us.

Thanks!
