### ISSUE TITLE
Pricing mismatch between Beta Plans and Sign Up pages

### ISSUE THREAD

**Issue by rsimplicio** [firesidelabs/fireside#42]
Pricing on the Beta Plans page is $14.99 for Beta One and $34.99 for Beta Two, but when clicking through on either option through the Get Started link, the Sign Up page shows the prices as $14.00 and $34.00, respectively.

**Comment by dan** [comment]
Do you recall the URL for this page?

**Comment by dan** [comment]
I think I found it.
