### ISSUE TITLE
Embedded player doesn't display episode-specific show art

### ISSUE THREAD

**Issue by tvreeh** [firesidelabs/fireside#43]
![capture 1](https://cloud.githubusercontent.com/assets/22915920/19484106/73d9be7a-9524-11e6-9bde-6f0d4297b87c.png)
Tried to the embed the Fireside player on a different website but I noticed it doesn't display episode-specific show art, just showing podcast show art. Possible enhancement to the embed code? Pasting my code here as an example:

`<iframe width="560" height="80" scrolling="no" frameborder="no" src="https://1pvs2p.fireside.fm/64/player/iframe"></iframe>`

**Comment by dan** [comment]
Fixed!
