### ISSUE TITLE
Google+ URL is Being Mangled

### ISSUE THREAD

**Issue by TerenceCGannon** [firesidelabs/fireside#45]
In the Social section of the Podcast Settings, I believe the Google+ URL is being slightly mangled when the settings are saved.  For example if I put 11459587______6972282 in as my pageId, the results URL on the Google+ button is https://plus.google.com/+11459587______6972282.  Note the errant '+'.  I'm pretty sure the resulting URL should be https://plus.google.com/11459587______6972282 (no '+').

**Comment by dan** [comment]
This is my Google+ URL:

`https://plus.google.com/+DanBenjamin`

It seems when I was writing this, I assumed that all Google+ URLs started with a +, but indeed, they do not. This has been fixed and will appear in the next deploy later today.

**Comment by TerenceCGannon** [comment]
Working in the wild, thanks @dan and team.
