### ISSUE TITLE
URL Link Directly to Show Chapters

### ISSUE THREAD

**Issue by TerenceCGannon** [firesidelabs/fireside#46]
It would be very handy to be able to tweet out links to specific chapters for an episode.  For example, there is an episode which includes discussion of Powell's Books for a couple of minutes.  I have created a chapter called "Powell's Books".  It would be great if I could share a link like (for example):

https://worknotwork.fireside.fm/003-thomas-pragmatic-3?c=powells-books

Wanting both to have and also eat my cake, it would be spectacular if when that link is clicked that it not only start playing at that chapter's timecode, but also for a **specified duration**.  Maybe the latter should be recorded as a separate issue?

**Comment by dan** [comment]
This is already in place, but won't work until chapters are fixed (by @chadbailey59 or myself).
