### ISSUE TITLE
Link with Timestamp Doesn't Appear to Work as Advertised

### ISSUE THREAD

**Issue by TerenceCGannon** [firesidelabs/fireside#47]
I tried sharing a Linked With Timestamp, as per:  

https://worknotwork.fireside.fm/003-thomas-pragmatic-3?t=1065

When I hit the play button, the episode starts at the beginning (t=0) rather than than the 1065th second, as expected with the timestamped URL as above. This is on an iMac running macOS Version 10.12 and Safari Version 10.0.

**Comment by dan** [comment]
I think this is due to not pre-loading the audio file, which now that we're changing how we're billing, I should be able to re-enable.

I'll follow up shortly.

**Comment by dan** [comment]
Fixed. Thanks so much for catching this!
