### ISSUE TITLE
MAILCHIMP INTEGRATION

### ISSUE THREAD

**Issue by jillymarie57** [firesidelabs/fireside#48]
Hi Dan!

At this point we plan to keep all brand affiliated items funnelled through our Fireside site. As a result, we need the functionality to keep GROWING OUR LIST for further email marketing!!

Can you set Mailchimp integration in the near future!!! 

LET US KNOW WHEN YOU HAVE AN ETA?!

Many Thanks, 

Jill

**Comment by dan** [comment]
Jill,

I've done this type of thing on 5by5.tv, how exactly would you like or imagine this to work?

Is there an example somewhere that you'd like to use as a starting point?
