### ISSUE TITLE
Embed.ly Support

### ISSUE THREAD

**Issue by TerenceCGannon** [firesidelabs/fireside#49]
In order to embed Fireside podcasts in Medium posts, becoming an Embed.ly provider is a requirement according to Medium Support.  The steps don't look too onerous (spoken by someone who doesn't have to write the code!).  See http://embed.ly/providers/new for specific details.

**Comment by dan** [comment]
I just wanted to add some detail here before I close this - in order to work with Embedly, we're required to use http://playerjs.io/, which I have no current plans to migrate to.

I'm not saying "no" because I think Medium support is important. I'll continue to think and investigate this option.

**Comment by robspages** [comment]
I need this too. Is there potential for doing it as a 4th sharing option rather than migrating the main player to it?
