### ISSUE TITLE
Share Button Overlapping When Using Alot of Networks Links

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#5]
If you set up most of the podcast app links (I've got all but TuneIn), the Share button that gets added to the list does not seem to fit anymore.

![Share Button Overlapping](https://d17oy1vhnax1f7.cloudfront.net/items/3U1a0E3F3d0W2C0I1F0y/Image%202016-10-04%20at%2011.41.41%20AM.png?v=27729c2b)

Seen at: https://rgbafm.fireside.fm/21

Expected Results: Button is added to the right or below but not overlapping

**Comment by vallieres** [comment]
Same thing happens on the Share page when you have all the podcast apps enabled.

![All apps](https://d17oy1vhnax1f7.cloudfront.net/items/403n0H0R1s170X0F2v3r/Image%202016-10-04%20at%2012.42.45%20PM.png?v=d6f2cdc8)

**Comment by dan** [comment]
This hurts to look at.

**Comment by bynines** [comment]
A fix has been pushed for testing/acceptance. Will deploy as soon as fix is accepted.
