### ISSUE TITLE
Episodes migrated to Fireside don't get artwork

### ISSUE THREAD

**Issue by shoemoneypod** [firesidelabs/fireside#50]
Hello!
A listener who just started listening from the beginning has (unbeknownst to him) let me know he doesn't see artwork on the early episodes. I've confirmed that episodes migrated to Fireside from Libsyn don't get default artwork assigned to them. New episodes that are uploaded directly to Fireside since the migration do get artwork. Old episodes look like this...
Is there something I should have done, or can do now to resolve the issue?
![img_0086](https://cloud.githubusercontent.com/assets/22759543/19725614/87b8acd6-9b54-11e6-9ed9-d0a82db01726.PNG)

**Comment by dan** [comment]
Did you have artwork added to your podcast before you ran the import? If not, no artwork will be added.

**Comment by shoemoneypod** [comment]
Is it possible to add after the fact? If I import the artwork into each episode page, will that do it?

**Comment by dan** [comment]
You can of course add the artwork back to each episode in the admin, just click Images and upload your artwork, and Fireside will add it to the mp3 file.

![screen shot 2016-10-28 at 11 01 04 am](https://cloud.githubusercontent.com/assets/219/19813119/f0517de0-9cfd-11e6-833d-344c89b345ba.png)

**Comment by shoemoneypod** [comment]
Hi again...
I tried to upload art to individual previously loaded episodes. When I choose the art and hit Save Episode, browser sits for very long time and ultimately gives me this.
It seems, though, that the art does upload, even with the error. Not 100% sure. 
<img width="628" alt="screen shot 2016-10-30 at 8 46 37 pm" src="https://cloud.githubusercontent.com/assets/22759543/19841449/4667fed0-9ee2-11e6-9c7f-034c7344dc85.png">

**Comment by dan** [comment]
Have you tried in the last week? I think you ran into a short-lived bug that we have since resolved. Sorry for your trouble.
