### ISSUE TITLE
Unlink homepage text, left corner and text over header image.

### ISSUE THREAD

**Issue by Joseluissf** [firesidelabs/fireside#51]
![title](https://cloud.githubusercontent.com/assets/23128766/19825734/f5d655f4-9d4a-11e6-887c-5c13c70f0a11.jpg)

It would be great to be able  to unlink the text that appears over the header image from the text next to the logo on the left corner. It’s redundant.

**Comment by Joseluissf** [comment]
Updated description, uploaded screenshot

**Comment by dan** [comment]
Easiest way for you to accomplish this would be for you to add some header code injection. You didn't provide your admin URL so I couldn't add a link for you, but you can navigate to your Advanced tab for that.
