### ISSUE TITLE
Feature: Track clicks on links in show notes

### ISSUE THREAD

**Issue by coryroush** [firesidelabs/fireside#52]
Just a minor feature request, hardly crucial but could be interesting over time... if we use the bookmarklet to add links in the show notes for an episode, can some kind of click-tracking be added to the "Links" tab on an episode page? Ideally, this would track clicks from any source, including those that come from the podcast website and the show notes embedded in various clients (Pocket Casts, iTunes, Overcast, etc.)

**Comment by dan** [comment]
This is a great feature idea for a future release, thank you!

**Comment by dan** [comment]
I've added this to our future roadmap.
