### ISSUE TITLE
Bug: Guest Lists on episodes lose their comma-separation after saving

### ISSUE THREAD

**Issue by coryroush** [firesidelabs/fireside#53]
You are currently asked to submit a comma-separated list of guests on individual episode pages, but as soon as you save the details, the comma is stripped out and the names appear as one long unseparated list in both the episode details page and in the embedded show notes on the website and in podcast clients.
![screenshot_20161031-085156](https://cloud.githubusercontent.com/assets/1691287/19855093/1ba2641c-9f49-11e6-997b-808cad48708c.png)

**Comment by coryroush** [comment]
I saw where this was fixed, thanks! I'm noticing that it's still present on the episode edit page, as shown in the screenshot below.
![screenshot 2016-11-01 12 22 19](https://cloud.githubusercontent.com/assets/1691287/19897282/db54f72c-a02d-11e6-9ec5-a8e695085f9f.png)

**Comment by dan** [comment]
Fixed.
