### ISSUE TITLE
Feature: "Special guests" index

### ISSUE THREAD

**Issue by coryroush** [firesidelabs/fireside#54]
Allow "special guests" on podcast episodes to work similar to tags, with their own pages/indexes and the ability to edit a guest's description and include links to social media accounts or other websites. 

When guests are on a specific episode, their page is updated to show links to that episode as well as all of their previous appearances on the same podcast. (For future versions of Fireside with network features, maybe this could extend across several shows, so that if I'm a guest on Dan's Show and Cory's Show, my page showed links to appearances on both.)

In the Slack chat you asked: "say you have fifty guests, how do you want to select the ones on that episode". I don't imagine it working exactly like hosts and co-hosts in this regard (where there are checkboxes) but more like the existing tags system, where you just enter their names (comma-separated). This could get tricky when it comes to similar names (two different Bob Smiths appearing on the same podcast) but I think it'd be easier and more functional than some kind of checkbox or drop-down system that listed EVERY guest that ever appeared on a show.

**Comment by dan** [comment]
Guests are already a type of tag, and work exactly the same way as tags. Adding pages/feeds for them is easy to do, however adding a bio/links to media accounts is not possible without a total reengineering of this aspect.

Thoughts?

**Comment by dan** [comment]
This is feature-complete and will drop any day now. Waiting on the amazing @bynines to finish the styling of the new pages.
