### ISSUE TITLE
Mobile Safari listen statistics should be attributed to iOS, not OS X

### ISSUE THREAD

**Issue by CameronBanga** [firesidelabs/fireside#55]
Copying over from Slack, but when viewing statistics for an episode or podcast, Mobile Safari downloads are attributed to OS X. It would be awesome if these counted toward iOS instead.

<img width="1263" alt="screen shot 2016-11-01 at 10 51 58 am" src="https://cloud.githubusercontent.com/assets/611354/19893908/4fa0d8ec-a021-11e6-90f3-cd7bb02df3cc.png">

**Comment by chadbailey59** [comment]
This was resolved with an update over the weekend. Thanks for your patience!

Chad

**Comment by jamesmontemagno** [comment]
Looking great btw :) notice the  update right away.
