### ISSUE TITLE
Web-based player timeline out of sync with the playhead

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#56]
This is a little hard to explain, so reference the attached screenshot. If you look at where the timeline is, I've hovered my mouse just ahead of that and I get tooltip showing 00:51:41 - which I assume if I clicked, I would jump to that spot in the podcast. If you look at where the playhead is currently on that same timeline at 00:52:19 - If I click on that spot (ahead of the playhead) it actually takes me back in time to match the tooltip.

<img width="374" alt="screen shot 2016-11-03 at 6 51 47 pm" src="https://cloud.githubusercontent.com/assets/2416372/19989743/a87f88f6-a1f6-11e6-82e9-b7a7c833fd3a.png">

Again, sorry, this is hard for me to articulate, so hopefully the screenshot helps you understand what I'm getting at.

I've found this to be happening on mac, running Safari 10, as well as Chrome 54. I haven't had a chance to test it on other platforms.

Also, interesting to note, the issue seems more pronounced the further into a show you get - it's pretty close to accurate in the first 10-15 minutes of a show, but after 45-50 minutes, the issue becomes much more apparent.

**Comment by danbetcher** [comment]
Further to this - and I can't be 100% certain - but it seems that clicking around on the timeline, jumping back and for through the episode triggers additional downloads in Fireside's metrics for each click..  Further testing will be required to confirm that, but I wanted to make a note of it.

**Comment by dan** [comment]
That's interesting, I haven't seen that before, we'll take a look.

**Comment by dan** [comment]
Should be fixed!
