### ISSUE TITLE
New Blank Pages & Nav

### ISSUE THREAD

**Issue by AngeloCoppola-WA** [firesidelabs/fireside#57]
Many podcasts offer stores, recommendation lists, etc. that require their own page.

Minimum requirements are likely:
- page title
- page url slug
- HTML editor or text box
- Option to include page in main navigation and name the nav menu entry 

Suggested stretch goals:
- Sub pages with subnavigation in the menu
- Custom banner images per page
- If a sidebar is implemented, option to exclude sidebar in custom pages
- Custom 404 page
- Per page header code injection

**Comment by dan** [comment]
This is feature-complete and will drop any day now.

**Comment by dan** [comment]
This was done a while back, sorry for the late close here.
