### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by AngeloCoppola-WA** [firesidelabs/fireside#58]
Suggestions:

- Place "Show Hosts" in the sidebar, and center the host images (looks wonky left-justified on mobile). Also, either allow customization of the header or rename to "Show Host" when there is only one host.
- Allow for the creation of custom HTML blocks that can be included in the sidebar ( these could be used for signup forms, ads, announcements, facebook and twitter widgets, etc.)
- Custom HTML sidebar blocks can be active or inactive, determining visibility
- Place a site-wide search in the sidebar
- Sidebar should responsively move to the bottom of the page on small screens.

**Comment by dan** [comment]
We should do all of this.

**Comment by dan** [comment]
And we did do all of this. Except the links part, which is coming in the new template.
