### ISSUE TITLE
Renderring Issues in Android / Chrome

### ISSUE THREAD

**Issue by AngeloCoppola-WA** [firesidelabs/fireside#59]
These issues are showing up in Android / Chrome running on a Samsung Galaxy S6 Edge Plus.

1. Part of the Podcast title is being moved down into the image. Moving to landscape corrects this and then when rotating back to portrait the title displays correctly on one line across the top.

2. I have no idea where the blurred "w" and "i" are coming from.

Note: neither of these errors appear in the Opera browser on the same device.

![hnb-android-chrome](https://cloud.githubusercontent.com/assets/23267115/20020506/de8f9a56-a28e-11e6-904a-798179fe1aeb.jpg)

**Comment by bynines** [comment]
Title has been removed from top bar, so this is no longer occurring.
