### ISSUE TITLE
Tag Search Results Ordered by Oldest First

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#6]
When loading an episode tag, the results go from oldest to newest. Should probably be from newest to oldest IMHO.

![Episodes from oldest to newest](https://d17oy1vhnax1f7.cloudfront.net/items/1b3M15160T2f3x2F1Q0s/Image%202016-10-04%20at%2011.52.36%20AM.png?v=a145f8f3)

URL: https://rgbafm.fireside.fm/tags/iphone%207

Expected behaviour: Display from newest to oldest.

**Comment by dan** [comment]
These were originally sorted by `number`, but we switched to smart-slugs, and so needed to sort based on `publish_at` dates.
