### ISSUE TITLE
Download count is inaccurate

### ISSUE THREAD

**Issue by jakesutton** [firesidelabs/fireside#60]
I've previously noticed the download count get incremented with each reload of the episode edit page. I assumed it was something to do with the player on that page.

But now I'm seeing download counts for a show that doesn't even have an mp3 attached!

<img width="1048" alt="screen shot 2016-11-05 at 12 20 24 pm" src="https://cloud.githubusercontent.com/assets/24184/20032588/c3adadf8-a352-11e6-9116-5bb8fc9d0388.png">

(Safari 10.0.1 on macOS Sierra 10.12.1)

**Comment by coryroush** [comment]
I was just able to recreate the same issue - no mp3 attached, but when I clicked to preview the episode's page, it added 2 downloads to the count.

**Comment by dan** [comment]
Fixed on next deploy later today.
