### ISSUE TITLE
Header / Nav not rendering well

### ISSUE THREAD

**Issue by AngeloCoppola-WA** [firesidelabs/fireside#63]
I noticed this on the Shoe Money fireside site. The nav is being pushed down oddly due to the long podcast title, per the screenshot below. OS X Sierra / Chrome.

![screen shot 2016-11-05 at 4 41 15 pm](https://cloud.githubusercontent.com/assets/23267115/20034323/d4c832a6-a376-11e6-975a-a2173890bb68.png)

**Comment by bynines** [comment]
This has been resolved. Please, reopen if you see this reappear. Thank you for reporting!
