### ISSUE TITLE
Scrubbing through timeline in the web-based player triggers additional download counts

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#64]
In the web-based player, When clicking around on the timeline, jumping back and forth through an episode will trigger fireside to register an extra download for each click. If you spend a couple minutes bouncing around looking for a specific point in an episode, you can easily rack up 100s of extra downloads.

I didn't a little bit more testing on this, and found it to happen in Safari, but not in Chrome. It happens both on the public-facing web player, as well as the one in the Fireside admin panel. It seems to be something to do with the way different browsers are buffering the content. I'm not sure what could be done to solve this if the browser is requesting the file, it makes sense for Fireside to count the download.

The trouble is for a podcast like mine with a small audience, this can really skew the statistics which makes them somewhat unreliable/useless.

**Comment by dan** [comment]
This is just the nature of the Safari player, and there's nothing we can do about it. I wish we could fix it, but it's on Apple to make it right.
