### ISSUE TITLE
HTML flagged in iTunes / RSS Feed Validator

### ISSUE THREAD

**Issue by jillymarie57** [firesidelabs/fireside#65]
Podcast was rejected for the following reason(s):
 _itunes: summary should not contain HTML: em (8 occurrences)_

I've noticed the following: 
1) HTML markdowns on main iTunes description do not translate into iTunes. During validation phase, content actually shows all italics, underscores, etc.
2) HTML markdowns seem to have difficult translating for episode summary content as well.

**Comment by dan** [comment]
This was fixed!
