### ISSUE TITLE
Sponsorship copy not visible on Episode summary

### ISSUE THREAD

**Issue by jillymarie57** [firesidelabs/fireside#66]
After importing sponsor copy in the Sponsorship campaign, copy does not show on Episode summary page. For the time being, I have simply inserted the copy into the body of the episode description with markdown hyperlinks to the sponsor's website.

**Comment by dan** [comment]
Can you please provide a link to the page that is having this issue?

**Comment by jamesmontemagno** [comment]
I have not experienced this at all. Working here for me.

**Comment by dan** [comment]
This, I believe, is fixed.
