### ISSUE TITLE
Episode Index Page

### ISSUE THREAD

**Issue by koleross** [firesidelabs/fireside#68]
Some listeners have asked if it's possible to have a single page that shows a list of all of the available episodes. I'm asking for a feature that does just that: surfaces the episode archives in a way that is easily searchable/scannable.

**Comment by dan** [comment]
@koleross You're wanting a single (non-paginated) page of every single episode? Or are you wanting the ability to search episodes?

**Comment by koleross** [comment]
A single non-paginated list of episodes for people to glance at would be
useful, especially for shows that have a longer run. I’ve had some
listeners express frustration at paging through episodes 5-10 at a time.

I wouldn’t need it to load the cover images… the list could just be a table
of text, or an unordered list of text links.

On February 9, 2017 at 5:53:49 PM, Dan Benjamin (notifications@github.com)
wrote:

@koleross <https://github.com/koleross> You're wanting a single
(non-paginated) page of every single episode? Or are you wanting the
ability to search episodes?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/firesidelabs/fireside/issues/68#issuecomment-278801567>,
or mute the thread
