### ISSUE TITLE
No way to preview podcast when in draft mode

### ISSUE THREAD

**Issue by idbjorh** [firesidelabs/fireside#69]
If a new podcast is in Draft mode, there is no way to preview the site.

When logged in to the admin site, going to http://createdb.fireside.fm results in the error page “The page you were looking for doesn’t exist” 

Similarly, if I click on the "View" link for a particular episode, I get the same error message.

My [Admin page](https://createdb.fireside.fm/admin)

**Comment by idbjorh** [comment]
One additional comment:  I'm referring to situation when the entire *podcast* is in draft mode - not jus an individual episode.

**Comment by dan** [comment]
I think this is a really useful idea, and there's now kind-of a way to do it.

In advanced settings, check the "Hide my website from search engines" box, and it will do exactly what you think it would.

This won't stop somebody from somehow stumbling onto your podcast, but it won't be indexed by search engines.

I hope this will address the issue.
