### ISSUE TITLE
Subscribe Via Block Missing Podcast Apps Button

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#7]
From the tag search results, we have a _Subscribe via_ row with Overcast, PocketCast, etc. But after setting all of the podcast apps URL in Settings, we are still missing Sticher and TuneIn.

![Missing App Buttons](https://d17oy1vhnax1f7.cloudfront.net/items/3D2q333o2J2A1c1t0L2y/Image%202016-10-04%20at%2011.54.51%20AM.png?v=8a0132d7)

URL: https://rgbafm.fireside.fm/tags/iphone%207

Expected Results: Show all of the podcast app buttons as we have on other pages

**Comment by dan** [comment]
Fixed, nice catch.
