### ISSUE TITLE
Podcast in Draft Mode Warning Message wrong link 

### ISSUE THREAD

**Issue by idbjorh** [firesidelabs/fireside#70]
When a podcast is in draft mode, a banner appears that the top of the page:

![screen shot 2016-12-07 at 10 41 15 am](https://cloud.githubusercontent.com/assets/8976239/20979380/f4c11f9e-bc69-11e6-9a23-4a3d5cf88dc2.png)

The link in this message links to my account settings page – https://fireside.fm/settings/subscription and not the podcast's settings page https://*podcast*.fireside.fm/admin/settings

**Comment by dan** [comment]
Fixed (long ago)!
