### ISSUE TITLE
Sponsors - Episodes Tracking

### ISSUE THREAD

**Issue by johnmgennaro** [firesidelabs/fireside#71]
I have a product request that I think might already exist and just need to be turned on....

Under sponsors: On the campaign screen itself, it tells me how many episodes that campaign has been a part of (for example "6 episodes"). However, it does not tell me WHICH episodes that campaign has been a part of. I have to go digging through each episode individually and check the sponsorship tab.

If there could be any way to turn that "6 episodes" into a link that tells me which 6 episodes, it would be incredibly helpful.

**Comment by dan** [comment]
Nice feature idea!

**Comment by dan** [comment]
Done!

**Comment by johnmgennaro** [comment]
Thank you!!
