### ISSUE TITLE
Avatar Image Upload

### ISSUE THREAD

**Issue by koleross** [firesidelabs/fireside#72]
When creating a Guest profile, I tried uploading an avatar image that I downloaded from elsewhere on Fireside. It appears that if the image is using a reserved name (in this case "avatar-small.jpg") causes Fireside to kick back an "Oops, something went wrong!" image. Renaming the avatar image solved this issue, but it might be worth looking at a new failure state for that action.

**Comment by Lehi79** [comment]
I'd like to +1 on this, I also had this issue.

**Comment by dan** [comment]
Interesting, this is a bug.
