### ISSUE TITLE
Feature: Daily Podcast Stats

### ISSUE THREAD

**Issue by chadadada17** [firesidelabs/fireside#73]
I was told to leave this here.

I think it would be cool to have a page for daily stats. In my head, I'd look at the Metrics page, click on a date from the Overall Downloads graph, and be able to see all activity from that day: what was downloaded and how many times, what clients were predominantly used, and locations downloaded from. So, basically what you see for individual stats on a single episode, but cumulative for all episodes on the specific date.

Also, adding a brief glimpse at Daily Totals (maybe just a small chart of episodes downloaded that day and how many times) to the main Metrics page that I could then click through to see the more detailed daily breakdown.

Just a thought! Thanks guys!

**Comment by dan** [comment]
I like this idea.
