### ISSUE TITLE
Metrics page progress bars are unreadable under 20%

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#75]
The text in the various progress bars on the Metrics page (Like Operating Systems, Downloads, etc.) are unreadable unless they are over about 20% full.  When they are less than that, the white labels are on a very light grey background which makes it hard to read.

See screenshot for example:
<img width="185" alt="screen shot 2016-12-18 at 10 39 15 am" src="https://cloud.githubusercontent.com/assets/2416372/21294921/90601836-c50e-11e6-95e8-024f6089a11d.png">

Possible solution would be to have the label switch color when it's >20%. Even better would be to pick a colour that is readable on either background. Black might work better:
<img width="174" alt="screen shot 2016-12-18 at 10 42 48 am" src="https://cloud.githubusercontent.com/assets/2416372/21294932/e3fb64dc-c50e-11e6-8084-66e8f7e8b200.png">

**Comment by chadbailey59** [comment]
Good catch. I've fixed it. Thanks!
