### ISSUE TITLE
Feature Request / Bug: Episode cover art doesn't override podcast cover art in meta tags

### ISSUE THREAD

**Issue by kmelve** [firesidelabs/fireside#77]
#Does it makes sense if the image parts of the meta tags on episode pages are set to the episode cover art (if there is any), and have the podcast cover art as fallback? 

```html
<meta property="og:image" content="{episodeCoverart ? episodeCoverArt.url : podcastCoverArt.url}">
<meta name="twitter:image" content="{episodeCoverart ? episodeCoverArt.url : podcastCoverArt.url}">
```

**Comment by danbetcher** [comment]
You could also probably combine these meta tags into a single tag to prevent duplication:

````html
<meta name="twitter:image" property="og:image" content="{episodeCoverart ? episodeCoverArt.url : podcastCoverArt.url}">

**Comment by dan** [comment]
Fixed, will go out on the next deploy.

Won't be combining tags, even though technically that _should_ work, neither Twitter nor Facebook are reliable.
