### ISSUE TITLE
Bug: Mobile Safari should be grouped with iOS on Metrics page

### ISSUE THREAD

**Issue by jaxzin** [firesidelabs/fireside#78]
Mobile Safari is grouped in Mac OS X but should be grouped with iOS.
![image](https://cloud.githubusercontent.com/assets/224363/21828512/acc28182-d745-11e6-96ee-3ecda16d8945.png)

/cc @chadbailey59

**Comment by dan** [comment]
@chadbailey59 Can you take a look?

**Comment by jaxzin** [comment]
This has been fixed with #89.
