### ISSUE TITLE
Long time, after episode refresh

### ISSUE THREAD

**Issue by Lehi79** [firesidelabs/fireside#79]
I'm spending a lot of times updating my episodes with the correct hosts, pictures, etc. after migrating 115 episodes.
I set up everything, and once I press "save episode" it takes minutes to actually get the green confirmation message, although if I look at the front end I can see that the update has been done already.
On some occasion I also get this:
"Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 843276
Varnish cache server"
It's not just when I upload a new cover art, it's even when I do a minor text modification.

**Comment by dan** [comment]
This was fixed!
