### ISSUE TITLE
TuneIn URL Not Saving under Settings

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#8]
When filling in the TuneIn URL with a valid TuneIn URL, and hitting save. The page reloads and the value is not saved.

![TuneIn Not Saved](https://d17oy1vhnax1f7.cloudfront.net/items/2S420R1K262y182H3f1j/Image%202016-10-04%20at%2011.57.43%20AM.png?v=70db3d92)

URL: /admin/settings

Expected Result: Result is saved and used across the site.

**Comment by dan** [comment]
Fixed (added to `params.require(:podcast).permit()` block).
