### ISSUE TITLE
[Feature Request] Sponsors - Ability to add a logo

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside#84]
This is a common request I get from sponsors. I know there is limited space due to coupon code area, but that could be reduced down if there is a logo.

**Comment by dan** [comment]
This is certainly doable, though I don't have an ETA on it.

@bynines what do you think for the size of this image?

**Comment by bynines** [comment]
@dan, currently, in this layout, horizontal space is more plentiful, so I'd say a rough size would be 100px (wide) by 200px (tall). Double that for retina screens.

**Comment by jamesmontemagno** [comment]
So I think maybe I was thinking of something else. I think most podcast episodes put the sponsors in the show notes so listeners can click on them. The "Sponsors" section to me should try its best to highlight the sponsor. If I had the ability to just have only logos of the sponsors that would be pretty click. Or the ability to display Logo or Text + promo code. This would be a huge win. Right now i just duplicate the text mostly from the show notes.
