### ISSUE TITLE
Twitter - add support for Twitter Cards preview

### ISSUE THREAD

**Issue by jaxzin** [firesidelabs/fireside#85]
When I post a link to a new episode on Twitter I would like it to appear as a card preview. This requires some additional `<meta>` elements be added to the episode page as described here:

http://stackoverflow.com/a/26537086

Specifically I'd like support for the Summary Card type:
https://dev.twitter.com/cards/types/summary

A more ambitious goal would be support for Player Card type so listeners could listen directly from their twitter timeline:
https://dev.twitter.com/cards/types/player

**Comment by jamesmontemagno** [comment]
I chatted with Dan on this and they do work, you just have to submit your site to twitter:

https://firesideteam.slack.com/archives/features/p1485518760000118

**Comment by jaxzin** [comment]
Thanks. For anyone else that finds there way here, you request whitelist approval by first validator your site here: https://cards-dev.twitter.com/validator  A "Request Approval" button will appear after trying to validate the link to one of your episodes (not the main site).
