### ISSUE TITLE
Social Share Episode Image

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#86]
When we share the link on social media, it picks up the cover art. Since show art is square and often social media prefer rectangular imagery, I propose to have a third option under images. 

*At the moment*
When you share to Facebook it shows this:
![Facebook Share](https://d17oy1vhnax1f7.cloudfront.net/items/1X0q3u2D302w143D1Z1d/Image%202017-02-03%20at%208.42.52%20AM.png?v=050fdd1f)

I propose a third image in the episode page where we could specify a rectangular image and achieve something that looks like this:

![Proposed Imagery](https://d17oy1vhnax1f7.cloudfront.net/items/2s2L0O0B0h1O281n3X0M/Image%202017-02-03%20at%208.46.17%20AM.png?v=004194f2)

We generate this sort of show art automatically for our episodes for this very purpose. Having it available as the default (or given a selection of which one we prefer out of the three) would be the best scenario.

Bonus points: if these images were also in the RSS feed, it could be picked up by IFTTT and Zapier for automatic publishing.

**Comment by dan** [comment]
This is interesting. Would the current header image not work for this?

**Comment by vallieres** [comment]
Due to the size of the image header and the text hovering over it in the podcast episode details page we resorted to use a large photo to illustrate the episode instead of custom episode art tha contains text and would look weird. 

exemple, at the moment we use a photo
![Photo](https://d17oy1vhnax1f7.cloudfront.net/items/1S1P0y3R0F1M0Y1j0X2G/Image%202017-02-09%20at%205.34.27%20PM.png?v=f6bc113d)

looks better than:
![Using episode art](https://d17oy1vhnax1f7.cloudfront.net/items/1T1Q3c472b2N3G1t0X0P/Image%202017-02-09%20at%205.35.51%20PM.png?v=a4c399a2)

And we think that this custom episode banner is better suited to social sharing as it fits well with its shape on Facebook, Twitter (even large photo Twitter cards), LinkedIn and (you might have guessed it) it's 16:9 so it's perfect for YouTube episode too for those sharing episodes on YT.

**Comment by dan** [comment]
I think this has been fixed.
