### ISSUE TITLE
[Feature Request] Https support for custom domains

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside#87]
Without Https support twitter cards will not validate and users get a nasty message when navigating to an https page:

![image](https://cloud.githubusercontent.com/assets/1676321/22658696/dc3f48e0-ec4f-11e6-8b4a-e2ea749f8596.png)

**Comment by dan** [comment]
That is correct, unfortunately. We are working on enabling https everywhere, but it's a lot of work and I do not currently have an ETA.

**Comment by dan** [comment]
Fixed.

**Comment by jamesmontemagno** [comment]
@dan anything i have to do to enable it or something rolling out in the future?
