### ISSUE TITLE
[Bug] Embed Player Links to Wrong URL with custom domain

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside#88]
See: http://motzcod.es/post/154607061227/xamarinforms-google-admob-ads-in-android

When you hover over art or link it says: http://mergeconflict.mergeconflict.fm :(

**Comment by dan** [comment]
Ugh, I see!

Fixing this right away, thank you.

**Comment by dan** [comment]
Fix goes out on the next deploy.
