### ISSUE TITLE
Youtube URL Could be Wrong (user vs. brand)

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#9]
When saving the podcast YouTube URL, you are saving it using this format: `https://www.youtube.com/user/RGBAfm`, however, some pages are "brand" pages and their channel URL is not the same format as the one for a "user". It can be referenced directly from the / or by adding a `/c/` before the channel name.

Expected Result: Offer saving everything after the first /. eg: `/c/RGBAfm` or `/user/AlexandreVallieresLagace` or `/RGBAfm`.

**YouTube**  `http://youtube.com/`  [ /c/RGBAfm ]

*URLs*
https://www.youtube.com/user/RGBAfm — Invalid
https://www.youtube.com/RGBAfm — Valid
https://www.youtube.com/c/RGBAfm — Valid
https://www.youtube.com/user/0xCAFE — Valid

**Comment by dan** [comment]
This should be switched to free-form URL so it's open to the user to enter as they choose.

**Comment by dan** [comment]
Fixed, will be in next deploy.
