### ISSUE TITLE
[Feature Request] Allow custom favicon.ico's

### ISSUE THREAD

**Issue by sanjay** [firesidelabs/fireside#90]
Would be nice to allow for a unique favicon.ico for the website which is separate from the Podcast's Cover Art.

**Comment by dan** [comment]
This is a neat idea. There are lots of implementation details to consider. For example, I suspect that many people would want to upload an image (as opposed to a precomposed .ico file) and have Fireside convert the image to the correct format. Even if a .ico file was uploaded, we'd still need to process it correctly, etc.

A nice idea for me to think about.

**Comment by sanjay** [comment]
It looks like y'all are using a scaled version (in my case a PNG) to set the favicon.ico link.  Most modern browsers don't need an actual .ico file and will render other formats.  Just need a way to set a different one.  We've got a smaller file that isn't our whole name that we could use for this - which is why I went looking for it.  :-)
