### ISSUE TITLE
Bug: Firefox doesn't render /subscribe page properly

### ISSUE THREAD

**Issue by sanjay** [firesidelabs/fireside#91]
The box where the RSS feed is supposed to show up on /subscribe renders properly in Chrome but not in Firefox.  I even tried to change the font color of the text to make sure it was rendering in black and that didn't do anything.

**Comment by dan** [comment]
What's the link to your site so we can reproduce it?

**Comment by sanjay** [comment]
http://www.techtalkyall.com/subscribe

Note that this *does* render properly on Firefox on Android.  Weird that desktop Firefox doesn't render properly.

**Comment by dan** [comment]
Fixed.
