### ISSUE TITLE
Language Templates

### ISSUE THREAD

**Issue by oskr989** [firesidelabs/fireside#92]
I would be nice to have a list of supported languages for the "front-end" webpage.
My podcasts are in Spanish, but the template is in English, so it might be confusing for a large part of our audience.
I will be happy to help with translating the template to Spanish, French and Portuguese, if you guys want.

**Comment by dan** [comment]
Thank you, and I would like to take you up on this soon.

**Comment by dan** [comment]
This is now on our roadmap.
