### ISSUE TITLE
[Feature Request] Associate Private guests with Podcast Episode

### ISSUE THREAD

**Issue by idbjorh** [firesidelabs/fireside#93]
Currently when a guest's status is Private, it is not possible to associate that guest with a podcast episode (i.e. the guest won't appear in the "Guests" section when editing a podcast episode).

This requires 2 steps to add a guest to a podcast episode:

1. Change guest's status to Public
2. Edit every episode the guest appears in to associate the (now publicly visible) guest.

It would be helpful to be able to associate "Private" guests with an episode – they should not be listed on any episodes' page while their profile is still private, but doing this will simplify the process of making guests visible when their status is changed to Public.

**Comment by dan** [comment]
You're right, but this isn't a feature request, it's a BUG! Thanks for finding it.

**Comment by dan** [comment]
This will roll out on the next deploy.
