### ISSUE TITLE
Google+ URL Removes the "+"

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#95]
I have this setup in the admin:

![Admin](https://d3uepj124s5rcx.cloudfront.net/items/173w32162A3H242J2M3m/Image%202017-02-22%20at%209.22.13%20AM.png?v=27733955)

And this is the URL on the right-side section: `https://plus.google.com/RGBAfm`
Missing the +

If I add the + in the field it works.

**Comment by dan** [comment]
Thanks, I'll remove the + from the left side. It was a remnant from the old way we used to handle these links.
