### ISSUE TITLE
[Feature Request] Open Episode Page Links in New Window (Sponsor,slugs,hosts)

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside#97]
I had a few listeners tell me they clicked on the sponsor and it opens in the same page so they lost their spot in the podcast.

For my show notes I will have to change everything over to html instead of markdown, which is on me, but there are several things on the episode that we can't control.

**Comment by dan** [comment]
I'm a strong believer that it should be up to the individual user as to if and how links open new tabs or pages. I'm opposed to having a website make this decision for me, and I don't want to make this decision globally for all Fireside users or their website visitors.

Adding a toggle of some kind to address this is an interesting idea, perhaps if more people chime in here, it would be something we could roadmap.

**Comment by jamesmontemagno** [comment]
Yeah, I guess the only thing I could think of is if they click a link and the player is playing audio then ask them if they want to leave, which is also annoying.
