### ISSUE TITLE
[Feature Request] allow usage of external dashboards

### ISSUE THREAD

**Issue by sanjay** [firesidelabs/fireside#99]
I use Geckoboard and it'd be nice to be able to pull in the episode download stats into that dashboard for a complete view of stats across platforms (Google Analytics, MailChimp subs, etc.).

**Comment by dan** [comment]
I think one day we will have a feature like this, but it's not on our near-term list of things to do, especially because of issues with long-term stat retention and aggregation. I'll keep this here though.
